# -*- coding: utf-8 -*-
"""polynomial_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B52x6M4zziga89x7ZEcikAhghtczKF2Y
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


np.random.seed(0)
points = 500
X = np.linspace(-3, 3, points)
#random value + y 
y = np.sin(X) + np.random.uniform(-0.5, 0.5, points)#y=sin(x)+variance

model = Sequential()
#we only need x input to make the prediction and therefore should be the dimension
model.add(Dense(50, activation='sigmoid', input_dim=1))
model.add(Dense(30, activation='sigmoid'))
model.add(Dense(1))
adam = Adam(lr=0.01)
model.compile(loss='mse', optimizer=adam)
model.fit(X, y, epochs=50)
predictions = model.predict(X)

plt.scatter(X, y)
plt.plot(X, predictions, 'ro')
plt.show()

